homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.Index, name='Index'),
    path('MyProfile', views.MyProfile, name='MyProfile'),
    path('Hobbies', views.Hobbies, name='Hobbies'),
    path('Education', views.Education, name='Education'),
    path('ExperienceAndSkills', views.ExperienceAndSkills, name='ExperienceAndSkills'),
    path('Favourites', views.Favourites, name='Favourites'),
    path('Story1', views.Story1, name='Story1'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def Index(request):
    return render(request, 'MyProfile.html')

def MyProfile(request):
    return render(request, 'MyProfile.html')

def Hobbies(request):
    return render(request, 'Hobbies.html')

def Education(request):
    return render(request, 'Education.html')

def ExperienceAndSkills(request):
    return render(request, 'ExperienceAndSkills.html')

def Favourites(request):
    return render(request, 'Favourites.html')

def Story1(request):
    return render(request, 'Story1.html')

homepage/templates/Education.html
{% extends "base.html" %}
{% load static %}

{% block title %}Education{% endblock %}

{% block background %}
<div class="bgFoto sekolah" class="img-fluid" alt="Responsive image"></div>
{% endblock %}

{% block ui %}
<div class="ui">
    <img src="{% static 'Makara_UI.png' %}" class="img-fluid" alt="Responsive image">
</div>
{% endblock %}

{% block isi %}
<div class="container-fluid">
    <div class="row">
        <div class="col-4 atur5">
            <h2 class="kuning share">Education</h1>
        </div>
        <div class="w-100"></div>
        <div class="col-4 atur6">
            <div class="putih share">
                SD Tunas Karya 2
                <br> 
                (2007-2013)
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-4 atur7">
            <div class="putih share">
                SMP 4 Kristen Penabur
                <br> 
                (2013-2016)
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-4 atur8">
            <div class="putih share">
                SMA Negri 21 Jakarta
                <br> 
                (2016-2019)
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-4 atur9">
            <div class="putih share">
                Universitas Indonesia
                <br> 
                (2019-...)
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
            </div>
        </div>
    </div>
</div>
{% endblock %}

homepage/templates/ExperienceAndSkills.html
{% extends "base.html" %}
{% load static %}

{% block title %}Experience and Skills{% endblock %}

{% block background %}
<div class="bgFoto ngoding" class="img-fluid" alt="Responsive image"></div>
{% endblock %}

{% block skills %}
<div class="java">
    <img src="{% static 'java.png' %}" class="img-fluid" alt="Responsive image">
</div>
<div class="python">
    <img src="{% static 'python.png' %}" class="img-fluid" alt="Responsive image">
</div>
<div class="html">
    <img src="{% static 'webb.png' %}" class="img-fluid" alt="Responsive image">
</div>
{% endblock %}

{% block isi %}
<div class="container-fluid">
    <div class="row">
        <div class="col-6 atur10">
            <h1 class="kuning share">Experience</h1>
        </div>
        <div class="w-100"></div>
        <div class="col-6 box atur11">
            <div class="putih share">
                <h2>- Staff Humas Paskah 2017 SMAN 21</h2>
                <h2>- Staff Perlengkapan Retreat 2018 SMAN 21</h2>
                <h2>- Ketua Perlengkapan Natal 2018 SMAN 21</h2>
                <h2>- Departemen Olahraga Sekolah BEM Fasilkom</h2>  
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-6 atur12">
            <h1 class="kuning share">Skills</h1>
        </div>
        <div class="w-100"></div>
        <div class="col-6 box atur13">
            <div class="putih share">
                <h2>- Python Programming Language</h2>
                <h2>- Java Programming Language</h2>
                <h2>- Web Design</h2>
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-6 atur12">
            <br>
            <br>
            <br>
        </div>
    </div>
</div>
{% endblock %}

homepage/templates/Favourites.html
{% extends "base.html" %}
{% load static %}

{% block title %}Favourites{% endblock %}

{% block background %}
<div class="bgFoto sushi" class="img-fluid" alt="Responsive image"></div>
{% endblock %}

  
{% block isi %}
      <div class="container-fluid">
          <div class="row">
              <div class="col-4 atur5">
                  <h2 class="kuning share">Favourites</h1>
              </div>
              <div class="w-100"></div>
              <div class="col-4 atur6">
                  <div class="kuning share ukur">
                      Food
                      <br>
                  </div>
                  <div class="putih share">
                      Sushi
                  </div>
              </div>
              <div class="w-100"></div>
              <div class="col-4 atur7">
                  <div class="kuning share ukur">
                      Drink
                      <br>
                  </div>
                  <div class="putih share">
                      Green Tea Frappuccino
                  </div>
              </div>
              <div class="w-100"></div>
              <div class="col-4 atur8">
                  <div class="kuning share ukur   ">
                      Film
                      <br>
                  </div>
                  <div class="putih share">
                      Nanti Kita Cerita Tentang Hari Ini
                  </div>
              </div>
              <div class="w-100"></div>
              <div class="col-4 atur9">
                  <div class="kuning share ukur   ">
                      Song
                      <br>
                  </div>
                  <div class="putih share">
                      Creep - Radiohead
                  </div>
              </div>
              <div class="col-2 atur14">
                <!-- Button trigger modal -->
  <button type="button" class="btn tombol kuning" data-toggle="modal" data-target="#exampleModal" style="background-color: #707070;">
    My Favourites carousel
    </button>
  
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="background-color: #38393C;">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="background-color: #707070;">
        <div class="modal-header">
            <h5 class="modal-title kuning" id="exampleModalLabel">My Gallery</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img class="d-block w-100" src="{% static 'sushi.jpg' %}" alt="First slide">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'greentea.jpg' %}" alt="Second slide">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'nkcthi.jpg' %}" alt="Third slide">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'creep.jpg' %}" alt="Third slide">
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
              </div>  
              </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn kuning" data-dismiss="modal" style="background-color: rgba(56, 57, 60, 0.692);">Close</button>
        </div>
        </div>
      </div>
</div>
</div>
  <div>
    <br>
    <br>
    <br>
    <br>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock %}

homepage/templates/Hobbies.html
{% extends "base.html" %}
{% load static %}

{% block title %}My Hobbies{% endblock %}

{% block background %}
<div class="bgFoto csgo" class="img-fluid" alt="Responsive image"></div>
{% endblock %}

{% block isi %}
<div class="container-fluid atur4">
    <div class="row">
        <div class="col-4">
            <h1 class="kuning tengah share">What I do for fun</h1>
        </div>

        <div class="w-100"></div>

        <div class="col-4 csblur fix" style="background-image: url('/static/cs.jpg');">
            <h1 class="kuning tengah share">Games</h1>
        </div>
        <div class="col-4"></div>
        <div class="col-2 top">
            <h1 class="kuning tengah share">Add Me</h1>
        </div>

        <div class="w-100"></div>

        <div class="col-4 spotblur" style="background-image: url('/static/spott.png');">
            <h1 class="kuning tengah share">Music</h1>
        </div>
        <div class="col-4"></div>
        <div class="col-2 mid">
            <h2 class="putih tengah share">Emlac</h2>
        </div>

        <div class="w-100"></div>

        <div class="col-4 vidblur" style="background-image: url('/static/vidd.jpg');">
            <h1 class="kuning tengah share">Stream</h1>
        </div>
        <div class="col-4"></div>
        <div class="col-2 bot">
            <h2 class="putih tengah share">Calmerjireh</h2>
        </div>

        <div class="w-100"></div>

        <div class="col-4">
            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
</div>
{% endblock %}

homepage/templates/MyProfile.html
{% extends "base.html" %}
{% load static %}

{% block title %}My Profile {% endblock %}

{% block background %}<div class="bgFoto kopi" class="img-fluid" alt="Responsive image"></div>{% endblock %}

{% block isi %}
<div class="container-fluid rounded">
    <div class="row">
        <div class="col-4 box atur1">
            <h2 class="kuning share">About Me</h1>
            <div class="putih share ukur">
                Sekarang menempuh pendidikan di
                <br> 
                Universitas Indonesia jurusan Ilmu Komputer.
                <br>
                <br>
                <br>
            </div>
        </div>
        <div class="col-5"></div>
        <div class="col-2 putih tengah paragraf atur2 oxygen">
            <p>Calmeryan Jireh</p>
            <p>19 years old</p>
            <p>Favourite color:</p>
            <p><span style="color: black;">Black</span> & <span style="color: #4D66E6;">Blue</span></p>
        </div>
        <div class="w-100"></div>
        <div class="col-9"></div>
        <div class="col-2 atur3 box">
            <h2 class="kuning tengah share">Contact</h2>
            <div class="w-100"></div>
            <div class="tengah share">
                <br>
                <img src="{% static 'line.png' %}" class="img-fluid icon1" alt="Responsive image"><b>calmeryan</b>
                <br>
                <br>
                <img src="{% static 'insta.png' %}" class="img-fluid icon1" alt="Responsive image"><a href="https://www.instagram.com/calmeryan/"><b>calmeryan</b></a>
                <br>
                <br>
                <img src="{% static 'facebook.png' %}" class="img-fluid icon1" alt="Responsive image"><a href="https://id-id.facebook.com/calmeryan.jireh"><b>calmeryan</b></a>
                <br>
                <br>
                <br>
            </div>
        </div>
    </div>
</div>
{% endblock %}

homepage/templates/Story1.html
<!DOCTYPE html>
{% load static %}

<html>

<head>
    <title>
        Calmeryan Jireh' Profile
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body">
    <div style="background: black;">
        <nav class="navbar navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'homepage:MyProfile' %}">My Profile</a>
            </div>
        </nav>
        <div class="container">
            <div class="m-3" style="position: relative">
                    <!-- Foto dan Nama -->
                    <span><img src="{% static 'FR13.jpg' %}" class="square" width="150"> </span>
                    <span class="text-light h2">Calmeryan Jireh</span>
            </div>

            <!-- Profile -->
            <div class="m-3 p-1 border rounded" style="background:rgb(83, 107, 155);">
                <b>Currently studying at University of Indonesia Computer Science</b>
                <div>Angkatan: Maung(2019)</div>
                <div>NPM: 1906292976</div>
            </div>
    
            <div class="m-3 p-2 border rounded" style="background: rgb(83, 107, 155);">
                <div class="h2">About Me</div>

                <div class="card mb-3">
                    <div class="card-body">
                        <p class="card-text">
                            Sekarang menempuh pendidikan di Universitas Indonesia jurusan Ilmu Komputer.
                            Orang yang sedikit introvert namun mudah untuk diajak bicara dan bercanda. Hobi saya adalah
                            rebahan, namun terkadang mengisi waktu kosong dengan bermain game atau mendengarkan musik.
                        </p>
                    </div>
                </div>
                
                <div class="h2">Riwayat Pendidikan</div>
    
                <table style="width:75%">
                    <tr>
                        <th>Tahun</th>
                        <th>Pendidikan</th>
                        <th>Sekolah/Universitas</th>
                    </tr>
                    <tr>
                        <td>2019-...</td>
                        <td>Sarjana(S1)</td>
                        <td>Universitas Indonesia</td>
                    </tr>
                    <tr>
                        <td>2016-2019</td>
                        <td>SMA</td>
                        <td>SMAN 21 Jakarta</td>
                    </tr>
                    <tr>
                        <td>2013-2016</td>
                        <td>SMP</td>
                        <td>SMPK 4 Penabur</td>
                    </tr>
                    <tr>
                        <td>2007-2013</td>
                        <td>SD</td>
                        <td>SD Tunas Karya 2</td>
                    </tr>
                </table>

                <div class="h2">Social Media</div>
                <p><img src="{% static 'line1.jpg' %}" class="square" width="25" height="25"> calmeryan</p>
                <p><img src="{% static 'ig1.jpg' %}" class="square" width="25" height="25"><a href="https://www.instagram.com/calmeryan/"> calmeryan</a></p>
            </div>
        </div>
        <nav class="navbar navbar-dark bg-dark">
        </nav>  
    </div>
</body>
</html>

homepage/templates/base.html
{% load static %}

<html>
    <head>
        <!-- Title -->
        <title>{% block title %}{% endblock title %}</title>

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oxygen|Share&display=swap">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>

    
    <body>
        <!--Navbar-->
        {% include "navbar.html" %}
    
        <!--Background-->
        {% block background %}
        {% endblock%}
        
        <!--3 Gambar hexagon-->
        <div class="foto1">
            <img src="{% static 'foto1.png' %}" class="img-fluid" alt="Responsive image">
        </div>
        <div class="foto2">
            <img src="{% static 'foto2.png' %}" class="img-fluid" alt="Responsive image">
        </div>
        <div class="hexagon">
            <img src="{% static 'hexagon.png' %}" class="img-fluid" alt="Responsive image">
        </div>
        {% block ui %}{% endblock %}
        {% block skills %}{% endblock %}

        <!--Isi-->
        {% block isi %}
        {% endblock %}
    </body>
</html> 

homepage/templates/navbar.html
<html>
    <body>
        <nav class="navbar navbar-custom">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'homepage:MyProfile' %}">My Profile</a>
              <ul class="nav navbar-brand navbar-right">
                <li><a href="{% url 'homepage:Hobbies' %}" class="navbar-brand">Hobbies</a></li>
              </ul>
              <ul class="nav navbar-brand navbar-right">
                <li><a href="{% url 'homepage:Education' %}" class="navbar-brand">Education</a></li>
              </ul>
              <ul class="nav navbar-brand navbar-right">
                <li><a href="{% url 'homepage:ExperienceAndSkills' %}" class="navbar-brand">Experience & Skills</a></li>
              </ul>
              <ul class="nav navbar-brand navbar-right">
                <li><a href="{% url 'homepage:Favourites' %}" class="navbar-brand">Favourites</a></li>
              </ul>
              <ul class="nav navbar-brand navbar-right">
                <li><a href="{% url 'homepage:Story1' %}" class="navbar-brand">Story1</a></li>
              </ul>
            </div>
        </nav>
    </body>
</html>